In [3]:
#pip install mlxtend

In [6]:
#pip install mlxtend

In [1]:
# Importation des librairies qu'on aura Ã  utiliser
from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder
import numpy as np
import pandas as pd
from scipy.io.arff import loadarff

In [2]:
# chargement du jeu de donnÃ©es et affichage de la structure
ligne, data = loadarff("C:/Program Files/Weka-3-8-6/data/supermarket.arff")
DFrame = pd.DataFrame(ligne)
long = len(DFrame)
DFrame.head()
print("la longueur du jeu de donnee est de: ", long)
print()
print("LLe nombre de lignes et de colonne: ", DFrame.shape)
DFrame

la longueur du jeu de donnee est de:  4627

LLe nombre de lignes et de colonne:  (4627, 217)

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'
1,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
2,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
3,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4623,b'?',b'?',b'?',b't',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'
4624,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4625,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4626,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'

In [3]:
# La liste des colonnes du supermarket
print(DFrame.columns)

Index(['department1', 'department2', 'department3', 'department4',
       'department5', 'department6', 'department7', 'department8',
       'department9', 'grocery misc',
       ...
       'department208', 'department209', 'department210', 'department211',
       'department212', 'department213', 'department214', 'department215',
       'department216', 'total'],
      dtype='object', length=217)

In [4]:
print(DFrame.department213)

0       b'?'
1       b'?'
2       b'?'
3       b'?'
4       b'?'
        ...
4622    b'?'
4623    b'?'
4624    b'?'
4625    b'?'
4626    b'?'
Name: department213, Length: 4627, dtype: object

In [5]:
# Ajoutons ces donnÃ©es dans une liste pour enfin les transformer avec transactionEncoder
list = []
for a in range(0, long):
    list.append([str(DFrame.values[a, b]) for b in range(0, 217)])
list=np.array(list)
print(list.shape)

(4627, 217)

Trnasformons nos donnees en un tableau croissant binair car la librairie que nous
allons utiliser prend en entree un tableau binaire

In [7]:
# transformons nos donnees en un tableau binaire car la librairie que nous allons utiliser
#ne prend en parametre que true ou false ou 1 et 0 
encod = TransactionEncoder()
trans = encod.fit(list).transform(list)
dat = pd.DataFrame(trans, columns=encod.columns_)
#dat
print("Affichons les 15 premieres ligne et les 2 premieres lignes de notre tableau binaire")  
dat.iloc[:15,:2]

Affichons les 15 premieres ligne et les 2 premieres lignes de notre tableau binaire

    b'?'  b'high'
0   True     True
1   True    False
2   True    False
3   True    False
4   True    False
5   True     True
6   True    False
7   True    False
8   True    False
9   True     True
10  True     True
11  True    False
12  True    False
13  True    False
14  True     True

In [8]:
#Affichons les itemsets frequents avec mun_sup = 0.03,

itemset_freq = fpgrowth(dat, min_support=0.03, use_colnames=True)
#print(itemset_freq.columns)
print(itemset_freq)

    support               itemsets
0   1.00000                 (b't')
1   1.00000                 (b'?')
2   0.36287              (b'high')
3   0.63713               (b'low')
4   1.00000           (b'?', b't')
5   0.36287        (b'?', b'high')
6   0.36287        (b'high', b't')
7   0.36287  (b'?', b'high', b't')
8   0.63713         (b'?', b'low')
9   0.63713         (b'low', b't')
10  0.63713   (b'?', b'low', b't')


Le dataframe itemset_freq contient deux colonnes la premiÃ¨re nommÃ©e Support et la deuxiÃ¨me nommÃ©e itemsets

In [9]:
print('regardons la structure c est-Ã -dire le nombre de ligne et de colonne de ce dataframe')
print(itemset_freq.shape)

regardons la structure c est-Ã -dire le nombre de ligne et de colonne de ce dataframe
(11, 2)

In [10]:
#trouvons les regles d'association avec les itemsets frequent via l'algo FPGrowth
Regles_Association_fpg =association_rules(itemset_freq, metric='confidence', min_threshold=0.4)
print(Regles_Association_fpg.shape)

(17, 9)

In [11]:
Regles_Association_fpg

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(b'?'),(b't'),1.00000,1.00000,1.00000,1.00000,1.0,0.0,inf
1,(b't'),(b'?'),1.00000,1.00000,1.00000,1.00000,1.0,0.0,inf
2,(b'high'),(b'?'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
3,(b'high'),(b't'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
4,"(b'?', b'high')",(b't'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
5,"(b'high', b't')",(b'?'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
6,(b'high'),"(b'?', b't')",0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
7,(b'?'),(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
8,(b'low'),(b'?'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
9,(b'low'),(b't'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
10,(b't'),(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
11,"(b'?', b'low')",(b't'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
12,"(b'?', b't')",(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
13,"(b'low', b't')",(b'?'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
14,(b'?'),"(b'low', b't')",1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
15,(b'low'),"(b'?', b't')",0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
16,(b't'),"(b'?', b'low')",1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0