In [50]:
#pip install apyori

In [197]:
import numpy as np
import pandas as pd
from scipy.io.arff import loadarff
from apyori import apriori
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules, apriori

In [198]:
# Ici on charge nos donnees, on les met dans deux variables (ligne et donnees), On cree une dataframe qui recois nos donnees puis on
#regarde la longeur avec la fonction lenth, on affiche l'entete des donnees avec la fonction head  enfin on regarde la structure du jeu de donnees
ligne, donnees = loadarff("C:/Program Files/Weka-3-8-6/data/supermarket.arff")
DFrame = pd.DataFrame(ligne)
long = len(DFrame)
DFrame.head()
print(long)
DFrame.shape
DFrame

4627

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'
1,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
2,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
3,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4623,b'?',b'?',b'?',b't',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'
4624,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4625,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4626,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'

In [199]:
# Avant de transforrmer ces données en tableau binair pour pouvoir faire l'extraction, voyons les noms des colonnes au préalable
print(DFrame.columns)

Index(['department1', 'department2', 'department3', 'department4',
       'department5', 'department6', 'department7', 'department8',
       'department9', 'grocery misc',
       ...
       'department208', 'department209', 'department210', 'department211',
       'department212', 'department213', 'department214', 'department215',
       'department216', 'total'],
      dtype='object', length=217)

In [272]:
# Ajoutons ces données dans une liste pour enfin les transformer avec transactionEncoder
list = []
for a in range(0, long):
    list.append([str(DFrame.values[a, b]) for b in range(0, 217)])
list=np.array(list)
print(list.shape)

(4627, 217)

In [274]:
#transformons nos donnees en un tableau binaire pour pouvoir les utiliser avec la librairie qui prend en entrée bool ou bin 
encod = TransactionEncoder()
trans = encod.fit(list).transform(list)
dat = pd.DataFrame(trans, columns=encod.columns_)
dat
#dat.shape

      b'?'  b'high'  b'low'  b't'
0     True     True   False  True
1     True    False    True  True
2     True    False    True  True
3     True    False    True  True
4     True    False    True  True
...    ...      ...     ...   ...
4622  True    False    True  True
4623  True     True   False  True
4624  True    False    True  True
4625  True    False    True  True
4626  True     True   False  True

[4627 rows x 4 columns]

In [286]:
# Utilisons la fonction apriori pour trouver les itemsets de supermarket

itemset_freq = apriori(dat,min_support=0.15, max_len=4,use_colnames=True)
#itemset_freq = apriori(dat, min_support=0.030, use_colnames=True)
print(itemset_freq)

    support               itemsets
0   1.00000                 (b'?')
1   0.36287              (b'high')
2   0.63713               (b'low')
3   1.00000                 (b't')
4   0.36287        (b'high', b'?')
5   0.63713         (b'low', b'?')
6   1.00000           (b't', b'?')
7   0.36287        (b'high', b't')
8   0.63713         (b't', b'low')
9   0.36287  (b'high', b't', b'?')
10  0.63713   (b't', b'low', b'?')

Le resultat nous que notre dataframe est vide, je ne crois pas à cela, dans la ligne qui suivrent nous allons utiliser un min_sup = 0.03

In [276]:
# Maintenant essayons de trouver les regles d'association avec les itemsets frequents trouvés via l'algo apriori 
regles_assoc = association_rules(itemset_freq, metric="confidence", min_threshold=0.4)
regles_assoc

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(b'high'),(b'?'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
1,(b'low'),(b'?'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
2,(b'?'),(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
3,(b't'),(b'?'),1.00000,1.00000,1.00000,1.00000,1.0,0.0,inf
4,(b'?'),(b't'),1.00000,1.00000,1.00000,1.00000,1.0,0.0,inf
5,(b'high'),(b't'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
6,(b't'),(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
7,(b'low'),(b't'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
8,"(b'high', b't')",(b'?'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
9,"(b'high', b'?')",(b't'),0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
10,(b'high'),"(b't', b'?')",0.36287,1.00000,0.36287,1.00000,1.0,0.0,inf
11,"(b't', b'low')",(b'?'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
12,"(b't', b'?')",(b'low'),1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
13,"(b'low', b'?')",(b't'),0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
14,(b't'),"(b'low', b'?')",1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0
15,(b'low'),"(b't', b'?')",0.63713,1.00000,0.63713,1.00000,1.0,0.0,inf
16,(b'?'),"(b't', b'low')",1.00000,0.63713,0.63713,0.63713,1.0,0.0,1.0

In [277]:
print(regles_assoc.shape)

(17, 9)

In [278]:
Regles_restreinte = regles_assoc.loc[:,['antecedents','consequents','lift']]
Regles_restreinte

        antecedents     consequents  lift
0         (b'high')          (b'?')   1.0
1          (b'low')          (b'?')   1.0
2            (b'?')        (b'low')   1.0
3            (b't')          (b'?')   1.0
4            (b'?')          (b't')   1.0
5         (b'high')          (b't')   1.0
6            (b't')        (b'low')   1.0
7          (b'low')          (b't')   1.0
8   (b'high', b't')          (b'?')   1.0
9   (b'high', b'?')          (b't')   1.0
10        (b'high')    (b't', b'?')   1.0
11   (b't', b'low')          (b'?')   1.0
12     (b't', b'?')        (b'low')   1.0
13   (b'low', b'?')          (b't')   1.0
14           (b't')  (b'low', b'?')   1.0
15         (b'low')    (b't', b'?')   1.0
16           (b'?')  (b't', b'low')   1.0